#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="cwops.csv"
URL="https://docs.google.com/spreadsheets/d/1Ew8b1WAorFRCixGRsr031atxmS0SsycvmOczS_fDqzc/gviz/tq?tqx=out:csv&sheet=Roster"
shortDesc="CWOps"
longDesc="CWOps"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
# Based on the web information, the records are updated at the end of each month
lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} |  awk -F"," 'NR>9 {print toupper($3)","$4",,"}' | sed 's/\"//g' >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

