#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="epc.csv"
URL="https://eupsk.club/documents/epc.txt"
shortDesc="EPC"
longDesc="European PSK Club"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | iconv -f utf8 -t ascii//IGNORE  | tr '#' '\n' | grep -v "^EPC" | grep -v -e " [[:digit:]]*L"  | grep -v '^[[:space:]]*$' | awk '{print toupper($2)","int($1)",,"}' | sort -t"," -k2 -n >> ${LISTS_DIR}/${memberFilename}

numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

