#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="eqslAGList.csv"
URL=http://www.eqsl.cc/qslcard/DownloadedFiles/AGMemberListDated.txt
shortDesc="eQSLAG"
longDesc="eQSL"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
lastUpdateNormalized=$(date +"%Y%m%d")

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | awk -F"," 'NR>2 {print toupper($1) ",,,"}'  >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

