#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="fists.csv"
URL=https://fists.co.uk/docs/fistsmembers.csv
shortDesc="FISTS"
longDesc="FISTS CW Club"
### END OF CONFIG

# Download File
downloadfile="${memberFilename}.raw"
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
headerLine=$(head -n 1 ${LISTS_DIR}/${downloadfile})
lastUpdate=$(echo "${headerLine}" | awk -F ',' '{print($4)}')
lastUpdateNormalized=$(date -d "${lastUpdate}" +"%Y%m%d")

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | awk -F ',' 'NR>1 {print toupper($2) "," $1 ",,"}' >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

