#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="foc.csv"
URL=https://g4foc.org/resources//Documents/Current.txt
shortDesc="FOC"
longDesc="First Class CW Operators"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
# Based on the web information, the records are updated at the end of each month
lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | awk -F'|' 'NR>3 {print toupper($1)"\n"$2}'  |sed -r 's/([[:digit:]]+)[[:space:]]+[A H][[:space:]]+([A-Z0-9]+)[[:space:]].*/\2,\1,,/' | sed 's/^[ \t]*//' >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

