#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="lids.csv"
URL="http://www.g4bki.com/call_history/lids.txt"
shortDesc="LIDS"
longDesc="The Less Involved Data Society"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
# Based on the web information, the records are updated at the end of each month
lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | awk -F"," '{print toupper($1)","$3",,"}' >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

