#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="naqcc.csv"
URL=http://naqcc.info/NAQCClistAlpha.txt
shortDesc="NAQCC"
longDesc="North American QRP CW Club"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
# Based on the web information, the records are updated at the end of each month
lastUpdateNormalized=$(date -d "$(date +%Y-%m-01) -1 day" +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | awk 'NR>2 {print toupper($1) "," $2 ",,"}'  >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

