#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="otc.csv"
URL="https://otc.cq.sk/zoznam-clenov-zoradeny-podla-clenskeho-cisla/"
shortDesc="OTC"
longDesc="Old-Timers Club SARA"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
# Based on the web information, the records are updated at the end of each month
lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
cat ${LISTS_DIR}/${downloadfile} | ./lib/html2csv.py -d ";" | awk -F";" 'function ltrim(s) { sub(/^[ \t\r\n]+/, "", s); return s }
function rtrim(s) { sub(/[ \t\r\n]+$/, "", s); return s } function trim(s)  { return rtrim(ltrim(s))} function removesk(s) {split(s,tmp,"-"); return trim(tmp[1]) }; NR>1{print removesk($2)","$1","trim($8)"-01-01,"}' >> ${LISTS_DIR}/${memberFilename}
numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

