#!/usr/bin/env bash

source lib/generic.sh

### CONFIG

memberFilename="qrqcrew.csv"
URL="https://www.qrqcrew.club/members.txt"
shortDesc="QRQCrew"
longDesc="QRQ Crew"
### END OF CONFIG

downloadfile="${memberFilename}.raw"

# Download file
downloadRet=$(downloadFile "${URL}" "${downloadfile}")

if [ $downloadRet != 0 ]; then
    echo "Cannot download a source file from ${URL}"
    exit 1;
fi

# Process Header
lastUpdateNormalized=$(sed -n '1s/^# Generated: \([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*/\1\2\3/p' ${LISTS_DIR}/${downloadfile})

[ -z "$d" ] && lastUpdateNormalized=$(date +%Y%m%d)

memberListHeader ${lastUpdateNormalized} > ${LISTS_DIR}/${memberFilename}

# Process Body
awk 'NF && !/^[[:space:]]*#/ { n=$NF; sub(/^#/, "", n); print $1 "," n ",," }' ${LISTS_DIR}/${downloadfile} >> ${LISTS_DIR}/${memberFilename}

numberRecord=$(wc -l < ${LISTS_DIR}/${memberFilename})

# Finalize
rm ${LISTS_DIR}/${downloadfile}
writeContentData "${shortDesc}" "${longDesc}" "${memberFilename}" "${lastUpdateNormalized}" "${numberRecord}"

